name: eeko-api
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  SPRING_PROFILES_ACTIVE: demo-env-value-from-secret
  TAG: 1.0.2

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Printer-image-build
        run: docker build  --build-arg SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE  -t 01720588884/printenv/printenv:1.0.0 .
      - name: Printer-image-push
        run: docker push 01720588884/printenv/printenv:1.0.0
